# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9a3b1d0b7eca0e9ca541526f78c80325ac6a564513b648c2ff5d901024dba5a48ea0c479312d93df4553ee89380189b5e8f6c9dd1512cd119e05ed1e3c89ba7

test:
  secret_key_base: 4c86b96af1f408769e191094ff1f9a6cb310b8411d923937ac7194342bda9116bba10968875c9ee6c78639640135813bf5793f2b0cf0954009952596c1ecf330

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
